<option value = 'Adipose tissue'>Adipose tissue</option>
<option value = 'Adrenal gland'>Adrenal gland</option>
<option value = 'Airway epithelial cells'>Airway epithelial cells</option>
<option value = 'Algae'>Algae</option>
<option value = 'Algal cells'>Algal cells</option>
<option value = 'AML cells'>AML cells</option>
<option value = 'Amniotic fluid'>Amniotic fluid</option>
<option value = 'Arteries'>Arteries</option>
<option value = 'Astrocyte cells'>Astrocyte cells</option>
<option value = 'Bacterial cells'>Bacterial cells</option>
<option value = 'Bacterial culture supernatant'>Bacterial culture supernatant</option>
<option value = 'B-cells'>B-cells</option>
<option value = 'Biofilm'>Biofilm</option>
<option value = 'Biopsy'>Biopsy</option>
<option value = 'Bladder'>Bladder</option>
<option value = 'Bladder tissue'>Bladder tissue</option>
<option value = 'Blood'>Blood</option>
<option value = 'Blubber'>Blubber</option>
<option value = 'Body tissue'>Body tissue</option>
<option value = 'Bone'>Bone</option>
<option value = 'Bone marrow'>Bone marrow</option>
<option value = 'Brain'>Brain</option>
<option value = 'Breast'>Breast</option>
<option value = 'Breast cancer cells'>Breast cancer cells</option>
<option value = 'Breast milk'>Breast milk</option>
<option value = 'Breast tissue'>Breast tissue</option>
<option value = 'Breath'>Breath</option>
<option value = 'Bronchoalveolar lavage'>Bronchoalveolar lavage</option>
<option value = 'Cecum'>Cecum</option>
<option value = 'Cells'>Cells</option>
<option value = 'Cerebrospinal fluid'>Cerebrospinal fluid</option>
<option value = 'Colon'>Colon</option>
<option value = 'Corpus luteum'>Corpus luteum</option>
<option value = 'Cortex'>Cortex</option>
<option value = 'Cultured cells'>Cultured cells</option>
<option value = 'Culture Media'>Culture Media</option>
<option value = 'Cyst fluid'>Cyst fluid</option>
<option value = 'Dental plaque'>Dental plaque</option>
<option value = 'Duodenum'>Duodenum</option>
<option value = 'Eggs'>Eggs</option>
<option value = 'Embryo'>Embryo</option>
<option value = 'Endothelial cells'>Endothelial cells</option>
<option value = 'Epididymal fat'>Epididymal fat</option>
<option value = 'Epithelial cells'>Epithelial cells</option>
<option value = 'Epithelial lining fluid'>Epithelial lining fluid</option>
<option value = 'Esophagus'>Esophagus</option>
<option value = 'Eye tissue'>Eye tissue</option>
<option value = 'Feces'>Feces</option>
<option value = 'Fibroblast cells'>Fibroblast cells</option>
<option value = 'Fish larvae'>Fish larvae</option>
<option value = 'Flushing'>Flushing</option>
<option value = 'Fly body'>Fly body</option>
<option value = 'Follicular fluid'>Follicular fluid</option>
<option value = 'Food item'>Food item</option>
<option value = 'Foreskin tissue'>Foreskin tissue</option>
<option value = 'Fungal cells'>Fungal cells</option>
<option value = 'Ganglia'>Ganglia</option>
<option value = 'Glioma cells'>Glioma cells</option>
<option value = 'Gonads'>Gonads</option>
<option value = 'Head tissue'>Head tissue</option>
<option value = 'Heart'>Heart</option>
<option value = 'HEK cells'>HEK cells</option>
<option value = 'HeLa cells'>HeLa cells</option>
<option value = 'Hemolymph'>Hemolymph</option>
<option value = 'Hepatopancreas'>Hepatopancreas</option>
<option value = 'Hypothalamus'>Hypothalamus</option>
<option value = 'Insect brain'>Insect brain</option>
<option value = 'Insect tissue'>Insect tissue</option>
<option value = 'Intestine'>Intestine</option>
<option value = 'iPSC cells'>iPSC cells</option>
<option value = 'Jejunum'>Jejunum</option>
<option value = 'Keratinocytes'>Keratinocytes</option>
<option value = 'Kidney'>Kidney</option>
<option value = 'Larvae'>Larvae</option>
<option value = 'Leaf'>Leaf</option>
<option value = 'Leaves'>Leaves</option>
<option value = 'Leukemia cells'>Leukemia cells</option>
<option value = 'Liver'>Liver</option>
<option value = 'LnCap cells'>LnCap cells</option>
<option value = 'Lung'>Lung</option>
<option value = 'Lung and skeletal muscle'>Lung and skeletal muscle</option>
<option value = 'Lungs'>Lungs</option>
<option value = 'Lymph'>Lymph</option>
<option value = 'Lymphoma cells'>Lymphoma cells</option>
<option value = 'Macrophages'>Macrophages</option>
<option value = 'Maize endosperm'>Maize endosperm</option>
<option value = 'Maize kernel'>Maize kernel</option>
<option value = 'Marine particulate matter'>Marine particulate matter</option>
<option value = 'Media'>Media</option>
<option value = 'Mesenteric lymph'>Mesenteric lymph</option>
<option value = 'Milk'>Milk</option>
<option value = 'Mitochondria'>Mitochondria</option>
<option value = 'Mononuclear cells'>Mononuclear cells</option>
<option value = 'Multiple'>Multiple</option>
<option value = 'Muscle'>Muscle</option>
<option value = 'Mycelia'>Mycelia</option>
<option value = 'Mycoplasma'>Mycoplasma</option>
<option value = 'Myotubes'>Myotubes</option>
<option value = 'Nasal polyp tissue'>Nasal polyp tissue</option>
<option value = 'Neurons'>Neurons</option>
<option value = 'Neurospheres'>Neurospheres</option>
<option value = 'Neutrophils'>Neutrophils</option>
<option value = 'Optic nerve'>Optic nerve</option>
<option value = 'Ovarian cancer cells'>Ovarian cancer cells</option>
<option value = 'Ovary'>Ovary</option>
<option value = 'Pancreas'>Pancreas</option>
<option value = 'Peritoneal fluid'>Peritoneal fluid</option>
<option value = 'Placenta'>Placenta</option>
<option value = 'Plankton'>Plankton</option>
<option value = 'Plant'>Plant</option>
<option value = 'Plant tissues'>Plant tissues</option>
<option value = 'Plasmodium cells'>Plasmodium cells</option>
<option value = 'Prostate'>Prostate</option>
<option value = 'Proximal tubular cells'>Proximal tubular cells</option>
<option value = 'Retina'>Retina</option>
<option value = 'Rhizome'>Rhizome</option>
<option value = 'Roundworm cultures'>Roundworm cultures</option>
<option value = 'Saliva'>Saliva</option>
<option value = 'Sap'>Sap</option>
<option value = 'Sarcoma'>Sarcoma</option>
<option value = 'Scalp'>Scalp</option>
<option value = 'Sciatic nerve'>Sciatic nerve</option>
<option value = 'Sea ice core'>Sea ice core</option>
<option value = 'Seeds'>Seeds</option>
<option value = 'Shrimp organs'>Shrimp organs</option>
<option value = 'Skin'>Skin</option>
<option value = 'Smooth muscle'>Smooth muscle</option>
<option value = 'Spinal cord'>Spinal cord</option>
<option value = 'Spleen'>Spleen</option>
<option value = 'Sputum'>Sputum</option>
<option value = 'Stem cells'>Stem cells</option>
<option value = 'Stomach'>Stomach</option>
<option value = 'Stool'>Stool</option>
<option value = 'Subcutaneous fat'>Subcutaneous fat</option>
<option value = 'Suspended Marine Particulate Matter'>Suspended Marine Particulate Matter</option>
<option value = 'Sweat'>Sweat</option>
<option value = 'Synthetic'>Synthetic</option>
<option value = 'Tail'>Tail</option>
<option value = 'T-cells'>T-cells</option>
<option value = 'Testis'>Testis</option>
<option value = 'Thyroid'>Thyroid</option>
<option value = 'Tissue'>Tissue</option>
<option value = 'Tissue and skeleton'>Tissue and skeleton</option>
<option value = 'Tongue Tissue'>Tongue Tissue</option>
<option value = 'Tumor cells'>Tumor cells</option>
<option value = 'Ulcer biopsies'>Ulcer biopsies</option>
<option value = 'Urine'>Urine</option>
<option value = 'Uterine fluid'>Uterine fluid</option>
<option value = 'Uterus'>Uterus</option>
<option value = 'Vaginal tissue'>Vaginal tissue</option>
<option value = 'Various'>Various</option>
<option value = 'Ventricles'>Ventricles</option>
<option value = 'Vitreous'>Vitreous</option>
<option value = 'Water'>Water</option>
<option value = 'Whole animal'>Whole animal</option>
<option value = 'Whole insect'>Whole insect</option>
<option value = 'Wine'>Wine</option>
<option value = 'Worms'>Worms</option>
<option value = 'Yeast cells'>Yeast cells</option>
